apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend http_front
        bind *:80
        default_backend app_backend

    backend app_backend
        balance roundrobin
        server app1 photostudio-service:3000 check