apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: photostudio-ns
data:
  haproxy.cfg: |
    defaults
        mode http
        timeout connect 5s
        timeout client 30s
        timeout server 30s

    frontend http_front
        bind *:8080
        mode http
        default_backend app_backend

    backend app_backend
        mode http
        balance roundrobin
        option httpchk

        server app1 photostudio-service:3000 check